### PR TITLE
Remove whitespace at end of lines

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil sw@weilnetz.de

### CODE REVIEW

**Comment by stweil** [comment]
Please review whether these whitespace changes are also fine for example texts and gold standards.

**Comment by kba** [comment]
I'm somewhat hesitant to merge this right now because it touches so many files. Right now, I prefer a clean blame history over good stylistic practice. But I'll be happy to revisit it next week.

The text files used as input to the algorithms should not be changed because they should be exactly like the output of our internal text extraction routines.

**Comment by stweil** [comment]
Blame history can ignore whitespace changes. The text examples will be removed in an updated patch.
I noticed that some text files don't use UTF-8 encoding. Is this intentional?

**Comment by stweil** [comment]
Updated and rebased patch, now only source files (java, xml, json, ...) are included.

**Comment by stweil** [comment]
Sorry, I pushed the wrong patch. Please wait for update.

**Comment by stweil** [comment]
Updated patch, now ready for pull.

**Comment by stweil** [comment]
Rebased patch to fix some merge conflicts.

**Comment by kba** [comment]
@Dommii @bolandka Since I'm not working on the Java codebase at the moment but you are, maybe one of you can merge this.

**Comment by bolandka** [comment]
Done. Thanks.

**Pull request merged**
